seg031 segment byte public 'STUNTSC' use16
    extrn file_load_shape2d_nofatal2:proc
    extrn file_combine_and_find:proc
    extrn file_find_next_alt:proc
    extrn nullsub_1:proc
    extrn nullsub_2:proc
    extrn init_main:proc
    extrn random_wait:proc
    extrn load_palandcursor:proc
    extrn get_0:proc
    extrn mmgr_alloc_resbytes:proc
    extrn mmgr_get_res_ofs_diff_scaled:proc
    extrn mmgr_get_chunk_size_bytes:proc
seg031 ends
