seg004 segment byte public 'STUNTSC' use16
    extrn build_track_object:proc
    extrn off_1F87E:word
    extrn bto_auxiliary1:proc
    extrn shape3d_load_all:proc
    extrn shape3d_free_all:proc
    extrn shape3d_load_car_shapes:proc
    extrn shape3d_free_car_shapes:proc
    extrn sub_204AE:proc
    extrn track_setup:proc
    extrn off_2147C:word
    extrn load_opponent_data:proc
    extrn subst_hillroad_track:proc
seg004 ends
