seg003 segment byte public 'STUNTSC' use16
    extrn sub_19F14:proc
    extrn init_rect_arrays:proc
    extrn update_frame:proc
    extrn skybox_op_helper2:proc
    extrn skybox_op:proc
    extrn transformed_shape_add_for_sort:proc
    extrn draw_track_preview:proc
    extrn draw_ingame_text:proc
    extrn do_sinking:proc
    extrn init_crak:proc
    extrn load_skybox:proc
    extrn unload_skybox:proc
    extrn load_sdgame2_shapes:proc
    extrn free_sdgame2:proc
    extrn setup_intro:proc
    extrn intro_op:proc
seg003 ends
