seg002 segment byte public 'STUNTSC' use16
    extrn ported_update_rpm_from_speed_:proc
    extrn nopsub_19DE8:proc
    extrn nopsub_19DFF:proc
    extrn nopsub_19E09:proc
    extrn nopsub_19E13:proc
    extrn ported_init_kevinrandom_:proc
    extrn ported_get_kevinrandom_seed_:proc
    extrn ported_get_kevinrandom_:proc
    extrn intr0_handler:proc
    extrn ported_init_div0_:proc
    extrn byte_19F07:byte
seg002 ends
