seg031 segment byte public 'STUNTSC' use16
    extrn ported_file_load_shape2d_nofatal2_:proc
    extrn ported_file_combine_and_find_:proc
    extrn ported_file_find_next_alt_:proc
    extrn nullsub_1:proc
    extrn nullsub_2:proc
    extrn ported_init_main_:proc
    extrn ported_random_wait_:proc
    extrn load_palandcursor:proc
    extrn ported_get_0_:proc
    extrn ported_mmgr_alloc_resbytes_:proc
    extrn ported_mmgr_get_res_ofs_diff_scaled_:proc
    extrn ported_mmgr_get_chunk_size_bytes_:proc
seg031 ends
