seg004 segment byte public 'STUNTSC' use16
    extrn build_track_object:proc
    extrn off_1F87E:word
    extrn bto_auxiliary1:proc
    extrn ported_shape3d_load_all_:proc
    extrn ported_shape3d_free_all_:proc
    extrn ported_shape3d_load_car_shapes_:proc
    extrn ported_shape3d_free_car_shapes_:proc
    extrn ported_sub_204AE_:proc
    extrn track_setup:proc
    extrn off_2147C:word
    extrn load_opponent_data:proc
    extrn subst_hillroad_track:proc
seg004 ends
